version: '3.9'

services:
  api:
    build: ./ImobiHub.API
    ports:
      - "5000:80"

  mysql:
    image: mysql:8
    container_name: imobihub-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: imobihub
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: